import type { NextPage } from 'next'
import { FaExternalLinkAlt } from "react-icons/fa";
import Head from 'next/head'
import Link from 'next/link'
import Urna from '../components/Urna/Urna'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Urna Eletrônica | HubCount</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/urna.ico" />
      </Head>

      <main className='mt-4'>
        <h2 className='text-center'>Eleições 2022</h2>
        <div className="d-block text-center">
          <Link href="/Cadastro">
            <a>Cadastro e listagem de candidatos <FaExternalLinkAlt/></a>
          </Link>
        </div>

        <div className="container">
          <div className="row align-items-center justify-content-center">
            <Urna className="col-md-8 mt-4"/>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
